[theme]
base = "light"
primaryColor = "#006B3F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF4F0"
textColor = "#111111"
font = "sans serif"

[server]
maxUploadSize = 25
enableStaticServing = false
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
